# DS 3000 - Assignment [3]

**Student Name**: [Ivan Ng]

**Date**: [1/28/2024]


### Submission Instructions
Submit this `ipynb` file to canvas.

The `ipynb` format stores outputs from the last time you ran the notebook.  (When you open a notebook it has the figures and outputs of the last time you ran it too).  To ensure that your submitted `ipynb` file represents your latest code, make sure to give a fresh run `Kernel > Restart & Run All` just before uploading the `ipynb` file to Canvas.

### Academic Integrity

**Writing your homework is an individual effort.**  You may discuss general python problems with other students but under no circumstances should you observe another student's code which was written for this assignment, from this year or past years.  Pop into office hours or DM us in MS Teams if you have a specific question about your work or if you would like another pair of eyes or talk through your code.

Don't forget to cite websites which helped you solve a problem in a unique way.  You can do this in markdown near the code or with a simple one-line comment. You do not need to cite the official python documentation.

**Documentation / style counts for credit**  Please refer to the Pep-8 style, to improve the readability and consistency of your Python code. For more information, read the following article [How to Write Beautiful Python Code With PEP 8](https://realpython.com/python-pep8/) or ask your TA's for tips.

**NOTE:<span style='color:red'> Write python expressions to answer ALL questions below and ensure that you use the `print()` function to display the output.</span>** Each question should be answered in a new code cell. For example, your solution for question 1.1 should be in a different code cell from your solution for question 1.2.

## Question 1: 

TODO: Copy/Paste the instructions for this question.


In [1]:
"""
Question 1: Analyzing Numeric Data (50 pts)

The data pertains to the risk factors associated with low infant birth weight**.
The data contains the following fields:

low
indicator of birth weight less than 2.5 kg.

age
mother's age in years.

lwt
mother's weight in pounds at last menstrual period.

race
mother's race (1 = white, 2 = black, 3 = other).

smoke
smoking status during pregnancy (0 = false, 1 = true).

ptl
number of previous premature labors.

ht
history of hypertension (0 = false, 1 = true).

ui
presence of uterine irritability.

ftv
number of physician visits during the first trimester.

bwt
birth weight in grams.

Write Python code to answer the questions below and ensure that you round all numeric calculations
(i.e. floats) to 2 decimal places (unless indicated otherwise).
Tip: you will need to filter for conditions that are true before performing certain calculations.
"""

"\nQuestion 1: Analyzing Numeric Data (50 pts)\n\nThe data pertains to the risk factors associated with low infant birth weight**.\nThe data contains the following fields:\n\nlow\nindicator of birth weight less than 2.5 kg.\n\nage\nmother's age in years.\n\nlwt\nmother's weight in pounds at last menstrual period.\n\nrace\nmother's race (1 = white, 2 = black, 3 = other).\n\nsmoke\nsmoking status during pregnancy (0 = false, 1 = true).\n\nptl\nnumber of previous premature labors.\n\nht\nhistory of hypertension (0 = false, 1 = true).\n\nui\npresence of uterine irritability.\n\nftv\nnumber of physician visits during the first trimester.\n\nbwt\nbirth weight in grams.\n\nWrite Python code to answer the questions below and ensure that you round all numeric calculations\n(i.e. floats) to 2 decimal places (unless indicated otherwise).\nTip: you will need to filter for conditions that are true before performing certain calculations.\n"

In [2]:
import numpy as np
# (5 pts) Load the attached data into a numpy array and display the dimensions of the data: birthwt.csv
file_name = "birthwt.csv"

with open(file_name, mode='r') as file:
    file.readline()
    data_list = []

    for line in file:
        values = line.strip().split(',')
        int_values = [int(value) for value in values]
        data_list.append(int_values)

    data_array = np.array(data_list)
    print(data_array)

[[   0   19  182 ...    1    0 2523]
 [   0   33  155 ...    0    3 2551]
 [   0   20  105 ...    0    1 2557]
 ...
 [   1   23   94 ...    0    0 2495]
 [   1   17  142 ...    0    0 2495]
 [   1   21  130 ...    0    3 2495]]


In [3]:
# (3 pts) What is the age range of mothers in this dataset?
# Note: the range should include: the minimum, average and maximum age. Ensure that the ages are
# represented as whole numbers.
age_column = data_array[:, 1]

min_age = np.min(age_column)
avg_age = round(np.mean(age_column), 2)
max_age = np.max(age_column)
range_age = max_age - min_age

print("Range:", range_age)
print("Minimum age:", min_age)
print("Average age:", avg_age)
print("Maximum age:", max_age)

Range: 31
Minimum age: 14
Average age: 23.24
Maximum age: 45


In [4]:
# (2 pts) How many mothers smoked during pregnancy?
smoke_column = data_array[:, 4]

total_smokers = np.sum(smoke_column)

print("Total smoking mothers:", total_smokers)

Total smoking mothers: 74


In [5]:
# (2 pts) How many mothers had a history of hypertension?
ht_column = data_array[:, 6]

total_ht = np.sum(ht_column)

print("Total mothers with hypertension:", total_ht)

Total mothers with hypertension: 12


In [6]:
# (3 pts) How many mothers have 1 or more premature births?
ptl_column = data_array[:, 5]

total_ptl = 0

for value in ptl_column:
    if value > 0:
        total_ptl += 1
        
print("Total mothers with 1+ premature births:", total_ptl)

Total mothers with 1+ premature births: 30


In [7]:
"""
(5 pts) Create a function called convert_birthweight() that: 
    1) takes grams as input, 
    2) converts grams to pounds and ounces, and 
    3) return the converted value. 
    Use the convert_birthweight() function to convert the birth weight to pounds and ounces
    in the questions 7-11 below.
"""
def convert_birthweight(grams):
    total_ounces = round(grams / 28.3495, 2)
    pounds = int(total_ounces // 16)
    remainder = round(total_ounces % 16, 2)
    return pounds, remainder

In [8]:
# (5 pts) What is the average birth weight of babies whose mothers have a history of premature birth?
bwt_column = data_array[:, 9]
ptl_bwt_column = []

for value in ptl_column:
    if value > 0:
        ptl_bwt_column.append(bwt_column[value])
        
avg_pounds, avg_remainder = convert_birthweight(np.mean(ptl_bwt_column))

print("Average weight of babies with mothers who have had premature birth:", avg_pounds, "lbs and", avg_remainder, "oz")

Average weight of babies with mothers who have had premature birth: 5 lbs and 10.07 oz


In [9]:
# (5 pts) What is the minimum, average and maximum birth weight of babies whose mother did not smoke
# during pregnancy and do not have a history of hypertension?
desired_bwt_column = []
for row in data_array:
    if row[4] + row[6] == 0:
        desired_bwt_column.append(row[9])

min_pounds, min_oz = convert_birthweight(np.min(desired_bwt_column))
avg_pounds, avg_oz = convert_birthweight(np.mean(desired_bwt_column))
max_pounds, max_oz = convert_birthweight(np.max(desired_bwt_column))

print("Minimun weight of no smoke or hypertension:", min_pounds, "lbs", min_oz, "oz")
print("Average weight of no smoke or hypertension:", avg_pounds, "lbs", avg_oz, "oz")
print("Maximum weight of no smoke or hypertension:", max_pounds, "lbs", max_oz, "oz")

Minimun weight of no smoke or hypertension: 2 lbs 4.01 oz
Average weight of no smoke or hypertension: 6 lbs 13.01 oz
Maximum weight of no smoke or hypertension: 11 lbs 0.02 oz


In [10]:
# (5 pts) What is the minimum, average and maximum birth weight of babies whose mothers smoked
# during pregnancy?
smoked_bwt_column = []
for row in data_array:
    if row[4] == 1:
        smoked_bwt_column.append(row[9])

smoked_min_pounds, smoked_min_oz = convert_birthweight(np.min(smoked_bwt_column))
smoked_avg_pounds, smoked_avg_oz = convert_birthweight(np.mean(smoked_bwt_column))
smoked_max_pounds, smoked_max_oz = convert_birthweight(np.max(smoked_bwt_column))

print("Minimun weight of smokers:", smoked_min_pounds, "lbs", smoked_min_oz, "oz")
print("Average weight of smokers:", smoked_avg_pounds, "lbs", smoked_avg_oz, "oz")
print("Maximum weight of smokers:", smoked_max_pounds, "lbs", smoked_max_oz, "oz")

Minimun weight of smokers: 1 lbs 9.01 oz
Average weight of smokers: 6 lbs 1.78 oz
Maximum weight of smokers: 9 lbs 5.49 oz


In [11]:
# (5 pts) What is the minimum, average and maximum birth weight of babies whose mothers had a
# history of hypertension?
ht_bwt_column = []
for row in data_array:
    if row[6] == 1:
        ht_bwt_column.append(row[9])

ht_min_pounds, ht_min_oz = convert_birthweight(np.min(ht_bwt_column))
ht_avg_pounds, ht_avg_oz = convert_birthweight(np.mean(ht_bwt_column))
ht_max_pounds, ht_max_oz = convert_birthweight(np.max(ht_bwt_column))

print("Minimun weight of hypertension:", ht_min_pounds, "lbs", ht_min_oz, "oz")
print("Average weight of hypertension:", ht_avg_pounds, "lbs", ht_avg_oz, "oz")
print("Maximum weight of hypertension:", ht_max_pounds, "lbs", ht_max_oz, "oz")

Minimun weight of hypertension: 2 lbs 8.04 oz
Average weight of hypertension: 5 lbs 9.48 oz
Maximum weight of hypertension: 8 lbs 5.69 oz


In [12]:
# (5 pts) What is the minimum, average and maximum birth weight of babies whose mothers smoked
# during pregnancy and had a history of hypertension?
op_desired_bwt_column = []
for row in data_array:
    if row[4] + row[6] == 2:
        op_desired_bwt_column.append(row[9])

op_min_pounds, op_min_oz = convert_birthweight(np.min(op_desired_bwt_column))
op_avg_pounds, op_avg_oz = convert_birthweight(np.mean(op_desired_bwt_column))
op_max_pounds, op_max_oz = convert_birthweight(np.max(op_desired_bwt_column))

print("Minimun weight of smoke and hypertension:", op_min_pounds, "lbs", op_min_oz, "oz")
print("Average weight of smoke and hypertension:", op_avg_pounds, "lbs", op_avg_oz, "oz")
print("Maximum weight of smoke and hypertension:", op_max_pounds, "lbs", op_max_oz, "oz")

Minimun weight of smoke and hypertension: 2 lbs 8.04 oz
Average weight of smoke and hypertension: 5 lbs 10.34 oz
Maximum weight of smoke and hypertension: 8 lbs 4.49 oz


In [14]:
"""
(5 pts) Compare and contrast the results from 7-11 above and summarize your findings.
Do you see any patterns in the birth weight of babies whose mother did not have any history of
hypertension and/or did not smoke during pregnancy versus those who did? Ensure that you reference
specific birth weights to support your explanation.
The lowest weight of the baby whose mother had a history of hypertension was also a smoker as the
minimum weight of mothers who had hypertension and mothers who had both are the same weight. Babies
born to none smokers or people with hypertension seem to be healthier as they are heavier on average.
They also have the highest weighing baby at around 11 pounds. The babies with hypertension seem to
weigh less on average as they have the lowest average and also bring down the average of babies born
to smokers.
"""

'\n(5 pts) Compare and contrast the results from 7-11 above and summarize your findings.\nDo you see any patterns in the birth weight of babies whose mother did not have any history of\nhypertension and/or did not smoke during pregnancy versus those who did? Ensure that you reference\nspecific birth weights to support your explanation.\nThe lowest weight of the baby whose mother had a history of hypertension was also a smoker as the\nminimum weight of mothers who had hypertension and mothers who had both are the same weight. Babies\nborn to none smokers or people with hypertension seem to be healthier as they are heavier on average.\nThey also have the highest weighing baby at around 11 pounds. The babies with hypertension seem to\nweigh less on average as they have the lowest average and also bring down the average of babies born\nto smokers.\n'